language: android
# Use the Travis Container-Based Infrastructure
sudo: false

jdk:
  - oraclejdk8

android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-23
    - extra-android-m2repository

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager --update

before_script:
  - chmod +x gradlew

script:
  - ./gradlew build
