language: android
# Use the Travis Container-Based Infrastructure
sudo: false

android:
  components:
    - build-tools-28.0.3
    - android-26

# Add license key to allow Android Gradle Plugin to download
# any missing dependencies not covered by above components.
# https://developer.android.com/studio/intro/update#download-with-gradle
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"

before_script:
  - chmod +x gradlew

script:
  - ./gradlew -version
  - ./gradlew assembleDebug
